p = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(p)}')
print(f'Só tem espaços? {p.isspace()}')
print(f'É um número? {p.isnumeric()}')
print(f'É alfabético? {p.isalpha()}')
print(f'É um alfanumérico? {p.isalnum()}')
print(f'Está em maiúsculo? {p.isupper()}')
print(f'Está em minúsculo? {p.islower()}')
print(f'Está capitalizada? {p.istitle()}')